[FLASK]

# Flask secret key for encrypting session objects
# Suggested: get key from https://randomkeygen.com
SECRET_KEY = Hithere10086!

# Toggle debug mode (allow repeat visits from same session)
# Accepts true or false
DEBUG = false

[PROLIFIC]

# Participant completion code on success
# Accepts string, or comment out for per-user codes
CODE_SUCCESS = C1LTJ0WA

# Participant completion code on reject
# Accepts string, or comment out for per-user codes
CODE_REJECT = C1KNKCLH

[IO]

# Path to metadata folder [default: ../metadata]
METADATA = ../metadata

# Path to data folder [default: ../data]
DATA = ../data

# Path to reject folder [default: ../reject]
REJECT = ../reject
